// Config Types
export const RESET_APP_STATE = 'RESET_APP_STATE'
export const SET_APP_THEME = 'SET_APP_THEME'

export const PLACEHOLDER_ACTION_TYPE = 'PLACEHOLDER_ACTION_TYPE'

// Users Action Types
export const GET_USERS_REQUEST = "GET_USERS_REQUEST"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_FAILURE = "GET_USERS_FAILURE"

export const GET_FILTERED_USERS_REQUEST = "GET_FILTERED_USERS_REQUEST"
export const GET_FILTERED_USERS_SUCCESS = "GET_FILTERED_USERS_SUCCESS"
export const GET_FILTERED_USERS_FAILURE = "GET_FILTERED_USERS_FAILURE"

// Devices Action Types
export const GET_DEVICES_REQUEST = "GET_DEVICES_REQUEST"
export const GET_DEVICES_SUCCESS = "GET_DEVICES_SUCCESS"
export const GET_DEVICES_FAILURE = "GET_DEVICES_FAILURE"

export const GET_FILTERED_DEVICES_REQUEST = "GET_FILTERED_DEVICES_REQUEST"
export const GET_FILTERED_DEVICES_SUCCESS = "GET_FILTERED_DEVICES_SUCCESS"
export const GET_FILTERED_DEVICES_FAILURE = "GET_FILTERED_DEVICES_FAILURE"